In [88]:
import keras
import tensorflow as tf
import mlflow
from mlflow.models import infer_signature
from hyperopt import fmin, tpe, hp, Trials, STATUS_OK
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_wine
from sklearn.metrics import mean_squared_error
import os

In [51]:
## load the dataset
data=pd.read_csv(
    "https://raw.githubusercontent.com/mlflow/mlflow/master/tests/datasets/winequality-white.csv",
    sep=";",
)
data

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
...,...,...,...,...,...,...,...,...,...,...,...,...
4893,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6
4894,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5
4895,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6
4896,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7
4897,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6

In [79]:
train, test= train_test_split(data, test_size=0.2, random_state=42)

train

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
4665,7.3,0.17,0.36,8.20,0.028,44.0,111.0,0.99272,3.14,0.41,12.4,6
1943,6.3,0.25,0.44,11.60,0.041,48.0,195.0,0.99680,3.18,0.52,9.5,5
3399,5.6,0.32,0.33,7.40,0.037,25.0,95.0,0.99268,3.25,0.49,11.1,6
843,6.9,0.19,0.35,1.70,0.036,33.0,101.0,0.99315,3.21,0.54,10.8,7
2580,7.7,0.30,0.26,18.95,0.053,36.0,174.0,0.99976,3.20,0.50,10.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
4426,6.2,0.21,0.52,6.50,0.047,28.0,123.0,0.99418,3.22,0.49,9.9,6
466,7.0,0.14,0.32,9.00,0.039,54.0,141.0,0.99560,3.22,0.43,9.4,6
3092,7.6,0.27,0.52,3.20,0.043,28.0,152.0,0.99129,3.02,0.53,11.4,6
3772,6.3,0.24,0.29,13.70,0.035,53.0,134.0,0.99567,3.17,0.38,10.6,6
860,8.1,0.27,0.35,1.70,0.030,38.0,103.0,0.99255,3.22,0.63,10.4,8

In [80]:
train[['quality']].values.ravel()

array([6, 5, 6, ..., 6, 6, 8], shape=(3918,))

In [94]:
train_x= train.drop('quality', axis=1).values
train_x

array([[ 7.3 ,  0.17,  0.36, ...,  3.14,  0.41, 12.4 ],
       [ 6.3 ,  0.25,  0.44, ...,  3.18,  0.52,  9.5 ],
       [ 5.6 ,  0.32,  0.33, ...,  3.25,  0.49, 11.1 ],
       ...,
       [ 7.6 ,  0.27,  0.52, ...,  3.02,  0.53, 11.4 ],
       [ 6.3 ,  0.24,  0.29, ...,  3.17,  0.38, 10.6 ],
       [ 8.1 ,  0.27,  0.35, ...,  3.22,  0.63, 10.4 ]], shape=(3918, 11))

In [81]:
train_x= train.drop('quality', axis=1).values
train_y= train[['quality']].values.ravel()

# test data
test_x= test.drop('quality', axis=1).values
test_y= test[['quality']].values.ravel()

# spliting data into train and validation
train_x, val_x, train_y, val_y= train_test_split(train_x, 
                                                 train_y,
                                                 test_size=0.2, 
                                                 random_state=42)
signature= infer_signature(train_x, train_y)

In [56]:
train_x.shape[1]

11

In [90]:
# ANN model
from hyperopt import STATUS_OK

def train_model(params, epochs, train_x, train_y, val_x, val_y, test_x, test_y):
    
    mean= train_x.mean(axis=0)
    var= train_x.var(axis=0)
    
    model= keras.Sequential(
        [
            keras.Input([train_x.shape[1]]),
            keras.layers.Normalization(mean= mean, variance= var),
            keras.layers.Dense(64, activation= 'relu'),
            keras.layers.Dense(32, activation= 'relu'),
            keras.layers.Dense(1)
        ]
    )
   
    
    model.compile(
        optimizer= keras.optimizers.SGD(learning_rate=params['learning_rate'],
                                         momentum= params["momentum"]),
        loss='mse',
        metrics=['mse']
    )
    
    with mlflow.start_run(nested= True):
        model.fit(
        train_x, train_y,
        validation_data=(val_x, val_y),
        epochs=epochs,
        batch_size=64,
        verbose=True)
        
        eval_result= model.evaluate(val_x, val_y, batch_size=64)
        
        eval_rmse= eval_result[1]
        
        mlflow.log_metric("eval_rmse", eval_rmse)
        
        # log model
        mlflow.tensorflow.log_model(model, "model", signature= signature)
        
        return {"loss": eval_rmse, 'status':STATUS_OK, 'model': model}

In [83]:
def objective(params):
    return train_model(params, epochs=10, 
                       train_x= train_x, 
                       train_y= train_y, 
                       val_x= val_x, 
                       val_y= val_y,
                       test_x= test_x,
                       test_y= test_y)
    return result

In [85]:
space= {
    'learning_rate': hp.uniform('learning_rate', 0.00001, 0.1),
    'momentum': hp.uniform('momentum', 0.0, 0.1)
}

In [86]:
# Disable the parts of autologging that are causing the schema crash
mlflow.tensorflow.autolog(
    log_models=False,           # Stops it from trying to save the .h5/.keras file
    log_model_signatures=False,  # Stops the TensorSpec validation error
    log_datasets=False           # Prevents issues with Pandas/Numpy conversion
)

In [91]:
mlflow.set_tracking_uri("http://127.0.0.1:5000")

mlflow.set_experiment("Wine_Quality_Local_v2")
with mlflow.start_run():
    trials = Trials()
    best = fmin(
        fn=objective,
        space=space,
        algo=tpe.suggest,
        max_evals=10, 
        trials=trials
    )
    
    # fetch the details of the best run
    best_run= sorted(trials.results, key= lambda x: x["loss"])[0]
    
    # log the best model parameters and metrics
    mlflow.log_params(best)
    mlflow.log_metric("best_eval_rmse", best_run["loss"])
    mlflow.tensorflow.log_model(best_run["model"], "model", signature=signature)
    
    # print the best hyperparameters and evaluation metric
    print("Best Hyperparameters:", best)    
    print("Best Evaluation RMSE:", best_run["loss"])

  0%|          | 0/10 [00:00<?, ?trial/s, best loss=?]

Epoch 1/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 46s 970ms/step - loss: 38.6304 - mse: 38.6304
13/49 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 14.0323 - mse: 14.0323
28/49 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 9.2046 - mse: 9.2046
43/49 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.0873 - mse: 7.0873
  0%|          | 0/10 [00:01<?, ?trial/s, best loss=?]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 2.4545 - mse: 2.4545 - val_loss: 0.6655 - val_mse: 0.6655

Epoch 2/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 51ms/step - loss: 0.6652 - mse: 0.6652
20/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6110 - mse: 0.6110
37/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6015 - mse: 0.6015
  0%|          | 0/10 [00:02<?, ?trial/s, best loss=?]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.5952 - mse: 0.5952 - val_loss: 0.4833 - val_mse: 0.4833

Epoch 3/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 45ms/step - loss: 0.5155 - mse: 0.5155
20/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4983 - mse: 0.4983
39/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5089 - mse: 0.5089
  0%|          | 0/10 [00:03<?, ?trial/s, best loss=?]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.5240 - mse: 0.5240 - val_loss: 0.4748 - val_mse: 0.4748

Epoch 4/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 47ms/step - loss: 0.2888 - mse: 0.2888
20/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4923 - mse: 0.4923
39/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4935 - mse: 0.4935
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.5070 - mse: 0.5070 - val_loss: 0.5581 - val_mse: 0.5581

Epoch 5/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 53ms/step - loss: 0.4446 - mse: 0.4446
19/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5117 - mse: 0.5117
39/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5103 - mse: 0.5103
  0%|          | 0/10 [00:04<?, ?trial/s, best loss=?]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.5074 - mse: 0.5074 - val_loss: 0.4667 - val_mse: 0.4667

Epoch 6/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 57ms/step - loss: 0.4648 - mse: 0.4648
19/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5713 - mse: 0.5713
36/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5523 - mse: 0.5523
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.5094 - mse: 0.5094 - val_loss: 0.4798 - val_mse: 0.4798

Epoch 7/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - loss: 0.2996 - mse: 0.2996
20/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4732 - mse: 0.4732
38/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4870 - mse: 0.4870
  0%|          | 0/10 [00:05<?, ?trial/s, best loss=?]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.5000 - mse: 0.5000 - val_loss: 0.4650 - val_mse: 0.4650

Epoch 8/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 45ms/step - loss: 0.4209 - mse: 0.4209
20/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4566 - mse: 0.4566
39/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4708 - mse: 0.4708
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4882 - mse: 0.4882 - val_loss: 0.4670 - val_mse: 0.4670

Epoch 9/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - loss: 0.6385 - mse: 0.6385
18/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4851 - mse: 0.4851
36/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4912 - mse: 0.4912
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.4775 - mse: 0.4775 - val_loss: 0.4888 - val_mse: 0.4888

Epoch 10/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 53ms/step - loss: 0.4231 - mse: 0.4231
19/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4785 - mse: 0.4785
37/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4891 - mse: 0.4891
  0%|          | 0/10 [00:06<?, ?trial/s, best loss=?]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.4776 - mse: 0.4776 - val_loss: 0.4539 - val_mse: 0.4539

 1/13 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.4334 - mse: 0.4334
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.4539 - mse: 0.4539

  0%|          | 0/10 [00:07<?, ?trial/s, best loss=?]

2026/05/01 12:12:46 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

🏃 View run selective-dog-987 at: http://127.0.0.1:5000/#/experiments/4/runs/98d2c24b7fcf4335baba2e2d6536c637

🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

 10%|█         | 1/10 [00:22<03:23, 22.59s/trial, best loss: 0.4538724422454834]

Epoch 1/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 48s 1s/step - loss: 35.9803 - mse: 35.9803
15/49 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 17.4228 - mse: 17.4228
30/49 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 11.9396 - mse: 11.9396
47/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.0734 - mse: 9.0734
 10%|█         | 1/10 [00:24<03:23, 22.59s/trial, best loss: 0.4538724422454834]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 3.2654 - mse: 3.2654 - val_loss: 0.5438 - val_mse: 0.5438

Epoch 2/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - loss: 0.7612 - mse: 0.7612
18/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5605 - mse: 0.5605
35/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5532 - mse: 0.5532
 10%|█         | 1/10 [00:25<03:23, 22.59s/trial, best loss: 0.4538724422454834]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.5589 - mse: 0.5589 - val_loss: 0.4931 - val_mse: 0.4931

Epoch 3/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 49ms/step - loss: 0.3788 - mse: 0.3788
21/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5494 - mse: 0.5494
41/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5468 - mse: 0.5468
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.5324 - mse: 0.5324 - val_loss: 0.5152 - val_mse: 0.5152

Epoch 4/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 3s 64ms/step - loss: 0.4302 - mse: 0.4302
17/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4935 - mse: 0.4935
33/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5030 - mse: 0.5030
48/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5074 - mse: 0.5074
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.5145 - mse: 0.5145 - val_loss: 0.5013 - val_mse: 0.5013

Epoch 5/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 56ms/step - loss: 0.5332 - mse: 0.5332
18/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4730 - mse: 0.4730
35/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4947 - mse: 0.4947
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.5087 - mse: 0.5087 - val_loss: 0.5015 - val_mse: 0.5015

Epoch 6/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 51ms/step - loss: 0.4391 - mse: 0.4391
18/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4989 - mse: 0.4989
36/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5039 - mse: 0.5039
 10%|█         | 1/10 [00:27<03:23, 22.59s/trial, best loss: 0.4538724422454834]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.4949 - mse: 0.4949 - val_loss: 0.4919 - val_mse: 0.4919

Epoch 7/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 51ms/step - loss: 0.4698 - mse: 0.4698
20/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5080 - mse: 0.5080
38/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4986 - mse: 0.4986
 10%|█         | 1/10 [00:27<03:23, 22.59s/trial, best loss: 0.4538724422454834]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.4953 - mse: 0.4953 - val_loss: 0.4694 - val_mse: 0.4694

Epoch 8/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 46ms/step - loss: 0.4230 - mse: 0.4230
19/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4986 - mse: 0.4986
38/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4934 - mse: 0.4934
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.4862 - mse: 0.4862 - val_loss: 0.4721 - val_mse: 0.4721

Epoch 9/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 3s 67ms/step - loss: 0.3482 - mse: 0.3482
17/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4917 - mse: 0.4917
37/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4949 - mse: 0.4949
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.4841 - mse: 0.4841 - val_loss: 0.4730 - val_mse: 0.4730

Epoch 10/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 57ms/step - loss: 0.3197 - mse: 0.3197
20/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4400 - mse: 0.4400
39/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4541 - mse: 0.4541
 10%|█         | 1/10 [00:28<03:23, 22.59s/trial, best loss: 0.4538724422454834]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.4815 - mse: 0.4815 - val_loss: 0.4679 - val_mse: 0.4679

 1/13 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.4981 - mse: 0.4981
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4679 - mse: 0.4679

 10%|█         | 1/10 [00:30<03:23, 22.59s/trial, best loss: 0.4538724422454834]

2026/05/01 12:13:08 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

🏃 View run traveling-bug-467 at: http://127.0.0.1:5000/#/experiments/4/runs/2867e30de2844c73ab3fa00887046828

🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

 20%|██        | 2/10 [00:44<02:59, 22.39s/trial, best loss: 0.4538724422454834]

Epoch 1/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 46s 962ms/step - loss: 34.7680 - mse: 34.7680
16/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 18.1049 - mse: 18.1049
33/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12.2383 - mse: 12.2383
 20%|██        | 2/10 [00:46<02:59, 22.39s/trial, best loss: 0.4538724422454834]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - loss: 4.0239 - mse: 4.0239 - val_loss: 1.5368 - val_mse: 1.5368

Epoch 2/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 55ms/step - loss: 1.6795 - mse: 1.6795
17/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.3331 - mse: 1.3331
34/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.2520 - mse: 1.2520
 20%|██        | 2/10 [00:47<02:59, 22.39s/trial, best loss: 0.4538724422454834]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 1.0772 - mse: 1.0772 - val_loss: 1.0979 - val_mse: 1.0979

Epoch 3/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 52ms/step - loss: 0.9034 - mse: 0.9034
17/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9460 - mse: 0.9460
33/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9079 - mse: 0.9079
 20%|██        | 2/10 [00:48<02:59, 22.39s/trial, best loss: 0.4538724422454834]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.8531 - mse: 0.8531 - val_loss: 0.8574 - val_mse: 0.8574

Epoch 4/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 52ms/step - loss: 0.4090 - mse: 0.4090
18/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6763 - mse: 0.6763
36/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7139 - mse: 0.7139
 20%|██        | 2/10 [00:48<02:59, 22.39s/trial, best loss: 0.4538724422454834]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.7183 - mse: 0.7183 - val_loss: 0.7248 - val_mse: 0.7248

Epoch 5/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 52ms/step - loss: 0.6094 - mse: 0.6094
19/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6643 - mse: 0.6643
37/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6547 - mse: 0.6547
 20%|██        | 2/10 [00:49<02:59, 22.39s/trial, best loss: 0.4538724422454834]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.6383 - mse: 0.6383 - val_loss: 0.6434 - val_mse: 0.6434

Epoch 6/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 49ms/step - loss: 0.6217 - mse: 0.6217
18/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5823 - mse: 0.5823
36/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5871 - mse: 0.5871
 20%|██        | 2/10 [00:49<02:59, 22.39s/trial, best loss: 0.4538724422454834]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.5920 - mse: 0.5920 - val_loss: 0.6179 - val_mse: 0.6179

Epoch 7/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 60ms/step - loss: 0.7429 - mse: 0.7429
17/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6070 - mse: 0.6070
36/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5839 - mse: 0.5839
 20%|██        | 2/10 [00:50<02:59, 22.39s/trial, best loss: 0.4538724422454834]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.5600 - mse: 0.5600 - val_loss: 0.5533 - val_mse: 0.5533

Epoch 8/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 52ms/step - loss: 0.5101 - mse: 0.5101
19/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5611 - mse: 0.5611
38/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5527 - mse: 0.5527
 20%|██        | 2/10 [00:51<02:59, 22.39s/trial, best loss: 0.4538724422454834]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.5380 - mse: 0.5380 - val_loss: 0.5284 - val_mse: 0.5284

Epoch 9/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 55ms/step - loss: 0.5330 - mse: 0.5330
20/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5489 - mse: 0.5489
37/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5490 - mse: 0.5490
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.5283 - mse: 0.5283 - val_loss: 0.5491 - val_mse: 0.5491

Epoch 10/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 60ms/step - loss: 0.5109 - mse: 0.5109
16/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4708 - mse: 0.4708
34/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4946 - mse: 0.4946
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.5158 - mse: 0.5158 - val_loss: 0.5421 - val_mse: 0.5421

 1/13 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.5190 - mse: 0.5190
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.5421 - mse: 0.5421

 20%|██        | 2/10 [00:53<02:59, 22.39s/trial, best loss: 0.4538724422454834]

2026/05/01 12:13:32 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

🏃 View run adventurous-vole-643 at: http://127.0.0.1:5000/#/experiments/4/runs/18e6ccee344148ad9d78f6b93422dc3a

🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

 30%|███       | 3/10 [01:08<02:40, 22.93s/trial, best loss: 0.4538724422454834]

Epoch 1/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 48s 1s/step - loss: 34.3953 - mse: 34.3953
14/49 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 11.0009 - mse: 11.0009
31/49 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.9020 - mse: 6.9020
47/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.4075 - mse: 5.4075
 30%|███       | 3/10 [01:10<02:40, 22.93s/trial, best loss: 0.4538724422454834]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - loss: 2.2732 - mse: 2.2732 - val_loss: 0.7351 - val_mse: 0.7351

Epoch 2/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 50ms/step - loss: 0.5787 - mse: 0.5787
17/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7749 - mse: 0.7749
34/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7591 - mse: 0.7591
 30%|███       | 3/10 [01:11<02:40, 22.93s/trial, best loss: 0.4538724422454834]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.7316 - mse: 0.7316 - val_loss: 0.5318 - val_mse: 0.5318

Epoch 3/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 47ms/step - loss: 0.7567 - mse: 0.7567
19/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.8212 - mse: 0.8212
37/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7831 - mse: 0.7831
 30%|███       | 3/10 [01:11<02:40, 22.93s/trial, best loss: 0.4538724422454834]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.6731 - mse: 0.6731 - val_loss: 0.5253 - val_mse: 0.5253

Epoch 4/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 47ms/step - loss: 0.6851 - mse: 0.6851
21/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5928 - mse: 0.5928
39/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5909 - mse: 0.5909
 30%|███       | 3/10 [01:12<02:40, 22.93s/trial, best loss: 0.4538724422454834]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.5584 - mse: 0.5584 - val_loss: 0.4835 - val_mse: 0.4835

Epoch 5/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 51ms/step - loss: 0.4720 - mse: 0.4720
19/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6805 - mse: 0.6805
38/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6289 - mse: 0.6289
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.5701 - mse: 0.5701 - val_loss: 0.5438 - val_mse: 0.5438

Epoch 6/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 46ms/step - loss: 0.3819 - mse: 0.3819
19/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6259 - mse: 0.6259
37/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6306 - mse: 0.6306
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6057 - mse: 0.6057 - val_loss: 0.5109 - val_mse: 0.5109

Epoch 7/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - loss: 0.5662 - mse: 0.5662
20/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5205 - mse: 0.5205
37/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5195 - mse: 0.5195
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.5264 - mse: 0.5264 - val_loss: 0.6273 - val_mse: 0.6273

Epoch 8/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 45ms/step - loss: 0.5801 - mse: 0.5801
21/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5766 - mse: 0.5766
39/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5617 - mse: 0.5617
 30%|███       | 3/10 [01:13<02:40, 22.93s/trial, best loss: 0.4538724422454834]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.5441 - mse: 0.5441 - val_loss: 0.4751 - val_mse: 0.4751

Epoch 9/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 58ms/step - loss: 0.6021 - mse: 0.6021
19/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5108 - mse: 0.5108
38/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5082 - mse: 0.5082
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.5431 - mse: 0.5431 - val_loss: 0.5178 - val_mse: 0.5178

Epoch 10/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - loss: 0.3756 - mse: 0.3756
19/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4714 - mse: 0.4714
39/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4853 - mse: 0.4853
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5172 - mse: 0.5172 - val_loss: 0.6223 - val_mse: 0.6223

 1/13 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.5581 - mse: 0.5581
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6223 - mse: 0.6223

 30%|███       | 3/10 [01:16<02:40, 22.93s/trial, best loss: 0.4538724422454834]

2026/05/01 12:13:55 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

🏃 View run unique-gnat-314 at: http://127.0.0.1:5000/#/experiments/4/runs/d0b15a0b276948f69de8ae0e5dab0872

🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

 40%|████      | 4/10 [01:31<02:16, 22.81s/trial, best loss: 0.4538724422454834]

Epoch 1/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 45s 944ms/step - loss: 31.5231 - mse: 31.5231
16/49 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 12.2313 - mse: 12.2313
32/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 8.2856 - mse: 8.2856
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4680 - mse: 6.4680
 40%|████      | 4/10 [01:32<02:16, 22.81s/trial, best loss: 0.4538724422454834]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - loss: 2.7045 - mse: 2.7045 - val_loss: 1.1513 - val_mse: 1.1513

Epoch 2/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - loss: 0.6814 - mse: 0.6814
19/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.8868 - mse: 0.8868
37/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.8683 - mse: 0.8683
 40%|████      | 4/10 [01:33<02:16, 22.81s/trial, best loss: 0.4538724422454834]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.8071 - mse: 0.8071 - val_loss: 0.7142 - val_mse: 0.7142

Epoch 3/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 49ms/step - loss: 0.8418 - mse: 0.8418
19/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6591 - mse: 0.6591
36/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6567 - mse: 0.6567
 40%|████      | 4/10 [01:34<02:16, 22.81s/trial, best loss: 0.4538724422454834]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.6394 - mse: 0.6394 - val_loss: 0.5889 - val_mse: 0.5889

Epoch 4/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 55ms/step - loss: 0.4713 - mse: 0.4713
20/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5418 - mse: 0.5418
39/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5558 - mse: 0.5558
 40%|████      | 4/10 [01:34<02:16, 22.81s/trial, best loss: 0.4538724422454834]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.5737 - mse: 0.5737 - val_loss: 0.5347 - val_mse: 0.5347

Epoch 5/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 50ms/step - loss: 0.6864 - mse: 0.6864
20/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5888 - mse: 0.5888
39/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5802 - mse: 0.5802
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.5389 - mse: 0.5389 - val_loss: 0.5377 - val_mse: 0.5377

Epoch 6/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 47ms/step - loss: 0.4038 - mse: 0.4038
19/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5091 - mse: 0.5091
37/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5200 - mse: 0.5200
 40%|████      | 4/10 [01:35<02:16, 22.81s/trial, best loss: 0.4538724422454834]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.5428 - mse: 0.5428 - val_loss: 0.5196 - val_mse: 0.5196

Epoch 7/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 47ms/step - loss: 0.6100 - mse: 0.6100
20/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5335 - mse: 0.5335
37/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5323 - mse: 0.5323
 40%|████      | 4/10 [01:36<02:16, 22.81s/trial, best loss: 0.4538724422454834]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.5381 - mse: 0.5381 - val_loss: 0.4907 - val_mse: 0.4907

Epoch 8/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 45ms/step - loss: 0.5304 - mse: 0.5304
20/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5250 - mse: 0.5250
40/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5216 - mse: 0.5216
 40%|████      | 4/10 [01:36<02:16, 22.81s/trial, best loss: 0.4538724422454834]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.5183 - mse: 0.5183 - val_loss: 0.4761 - val_mse: 0.4761

Epoch 9/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - loss: 0.6669 - mse: 0.6669
20/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5207 - mse: 0.5207
39/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5082 - mse: 0.5082
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5080 - mse: 0.5080 - val_loss: 0.4902 - val_mse: 0.4902

Epoch 10/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 46ms/step - loss: 0.5380 - mse: 0.5380
19/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4975 - mse: 0.4975
39/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5021 - mse: 0.5021
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.5022 - mse: 0.5022 - val_loss: 0.4801 - val_mse: 0.4801

 1/13 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.4824 - mse: 0.4824
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.4801 - mse: 0.4801

 40%|████      | 4/10 [01:39<02:16, 22.81s/trial, best loss: 0.4538724422454834]

2026/05/01 12:14:17 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

🏃 View run stylish-lamb-756 at: http://127.0.0.1:5000/#/experiments/4/runs/9371719731c44c71b5fdafadc83609d4

🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

 50%|█████     | 5/10 [01:54<01:54, 22.95s/trial, best loss: 0.4538724422454834]

Epoch 1/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 37s 790ms/step - loss: 34.5090 - mse: 34.5090
11/49 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 16.6581 - mse: 16.6581
28/49 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 10.3131 - mse: 10.3131
46/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7.6616 - mse: 7.6616
 50%|█████     | 5/10 [01:55<01:54, 22.95s/trial, best loss: 0.4538724422454834]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 2.8257 - mse: 2.8257 - val_loss: 0.7204 - val_mse: 0.7204

Epoch 2/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 50ms/step - loss: 0.7110 - mse: 0.7110
20/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5709 - mse: 0.5709
40/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5800 - mse: 0.5800
 50%|█████     | 5/10 [01:56<01:54, 22.95s/trial, best loss: 0.4538724422454834]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.5912 - mse: 0.5912 - val_loss: 0.4925 - val_mse: 0.4925

Epoch 3/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 50ms/step - loss: 0.3406 - mse: 0.3406
20/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5410 - mse: 0.5410
39/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5418 - mse: 0.5418
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5309 - mse: 0.5309 - val_loss: 0.5029 - val_mse: 0.5029

Epoch 4/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 51ms/step - loss: 0.4603 - mse: 0.4603
19/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5122 - mse: 0.5122
35/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5330 - mse: 0.5330
 50%|█████     | 5/10 [01:57<01:54, 22.95s/trial, best loss: 0.4538724422454834]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.5401 - mse: 0.5401 - val_loss: 0.4638 - val_mse: 0.4638

Epoch 5/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 44ms/step - loss: 0.4984 - mse: 0.4984
20/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5357 - mse: 0.5357
39/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5313 - mse: 0.5313
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.5219 - mse: 0.5219 - val_loss: 0.4722 - val_mse: 0.4722

Epoch 6/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - loss: 0.6412 - mse: 0.6412
21/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5043 - mse: 0.5043
40/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5009 - mse: 0.5009
 50%|█████     | 5/10 [01:58<01:54, 22.95s/trial, best loss: 0.4538724422454834]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.5065 - mse: 0.5065 - val_loss: 0.4611 - val_mse: 0.4611

Epoch 7/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 47ms/step - loss: 0.3780 - mse: 0.3780
21/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4662 - mse: 0.4662
39/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4726 - mse: 0.4726
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.5009 - mse: 0.5009 - val_loss: 0.5002 - val_mse: 0.5002

Epoch 8/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 46ms/step - loss: 0.4495 - mse: 0.4495
19/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5415 - mse: 0.5415
37/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5278 - mse: 0.5278
 50%|█████     | 5/10 [01:59<01:54, 22.95s/trial, best loss: 0.4538724422454834]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.5025 - mse: 0.5025 - val_loss: 0.4572 - val_mse: 0.4572

Epoch 9/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 55ms/step - loss: 0.2839 - mse: 0.2839
19/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4427 - mse: 0.4427
39/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4595 - mse: 0.4595
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.4923 - mse: 0.4923 - val_loss: 0.5553 - val_mse: 0.5553

Epoch 10/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 47ms/step - loss: 0.4981 - mse: 0.4981
19/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5282 - mse: 0.5282
38/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5071 - mse: 0.5071
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.4836 - mse: 0.4836 - val_loss: 0.4657 - val_mse: 0.4657

 1/13 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.5014 - mse: 0.5014
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4657 - mse: 0.4657

 50%|█████     | 5/10 [02:01<01:54, 22.95s/trial, best loss: 0.4538724422454834]

2026/05/01 12:14:40 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

🏃 View run unequaled-mule-50 at: http://127.0.0.1:5000/#/experiments/4/runs/9b4d8af1bdf44eef83e7aa1078b618c3

🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

 60%|██████    | 6/10 [02:16<01:31, 22.84s/trial, best loss: 0.4538724422454834]

Epoch 1/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 44s 926ms/step - loss: 35.3287 - mse: 35.3287
12/49 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 13.8506 - mse: 13.8506
27/49 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 10.2780 - mse: 10.2780
44/49 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.9704 - mse: 7.9704
 60%|██████    | 6/10 [02:18<01:31, 22.84s/trial, best loss: 0.4538724422454834]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - loss: 3.2756 - mse: 3.2756 - val_loss: 0.5614 - val_mse: 0.5614

Epoch 2/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 47ms/step - loss: 0.6533 - mse: 0.6533
18/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5706 - mse: 0.5706
36/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5601 - mse: 0.5601
 60%|██████    | 6/10 [02:19<01:31, 22.84s/trial, best loss: 0.4538724422454834]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.5548 - mse: 0.5548 - val_loss: 0.5026 - val_mse: 0.5026

Epoch 3/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - loss: 0.3887 - mse: 0.3887
21/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4830 - mse: 0.4830
40/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4999 - mse: 0.4999
 60%|██████    | 6/10 [02:20<01:31, 22.84s/trial, best loss: 0.4538724422454834]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.5305 - mse: 0.5305 - val_loss: 0.4994 - val_mse: 0.4994

Epoch 4/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 46ms/step - loss: 0.6215 - mse: 0.6215
19/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5429 - mse: 0.5429
34/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5326 - mse: 0.5326
 60%|██████    | 6/10 [02:20<01:31, 22.84s/trial, best loss: 0.4538724422454834]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.5176 - mse: 0.5176 - val_loss: 0.4613 - val_mse: 0.4613

Epoch 5/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 52ms/step - loss: 0.3891 - mse: 0.3891
19/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4754 - mse: 0.4754
36/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4995 - mse: 0.4995
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.5122 - mse: 0.5122 - val_loss: 0.4904 - val_mse: 0.4904

Epoch 6/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 52ms/step - loss: 0.4612 - mse: 0.4612
20/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4563 - mse: 0.4563
36/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4736 - mse: 0.4736
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4984 - mse: 0.4984 - val_loss: 0.4771 - val_mse: 0.4771

Epoch 7/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 53ms/step - loss: 0.3100 - mse: 0.3100
18/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4590 - mse: 0.4590
36/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4788 - mse: 0.4788
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.4935 - mse: 0.4935 - val_loss: 0.4723 - val_mse: 0.4723

Epoch 8/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 45ms/step - loss: 0.2882 - mse: 0.2882
20/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4514 - mse: 0.4514
36/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4626 - mse: 0.4626
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.4851 - mse: 0.4851 - val_loss: 0.4816 - val_mse: 0.4816

Epoch 9/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 49ms/step - loss: 0.5482 - mse: 0.5482
18/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4835 - mse: 0.4835
36/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4838 - mse: 0.4838
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.4794 - mse: 0.4794 - val_loss: 0.4658 - val_mse: 0.4658

Epoch 10/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 49ms/step - loss: 0.4060 - mse: 0.4060
20/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5024 - mse: 0.5024
38/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4962 - mse: 0.4962
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.4863 - mse: 0.4863 - val_loss: 0.4757 - val_mse: 0.4757

 1/13 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.4488 - mse: 0.4488
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4757 - mse: 0.4757

 60%|██████    | 6/10 [02:24<01:31, 22.84s/trial, best loss: 0.4538724422454834]

2026/05/01 12:15:03 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

🏃 View run carefree-frog-101 at: http://127.0.0.1:5000/#/experiments/4/runs/d300c4999d1445538fbcddd2ca33e9ac

🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

 70%|███████   | 7/10 [02:40<01:09, 23.22s/trial, best loss: 0.4538724422454834]

Epoch 1/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 46s 979ms/step - loss: 34.5593 - mse: 34.5593
15/49 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 12.4682 - mse: 12.4682
26/49 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 9.0941 - mse: 9.0941
40/49 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.0373 - mse: 7.0373
 70%|███████   | 7/10 [02:42<01:09, 23.22s/trial, best loss: 0.4538724422454834]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 2.4687 - mse: 2.4687 - val_loss: 0.8601 - val_mse: 0.8601

Epoch 2/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 49ms/step - loss: 0.8449 - mse: 0.8449
19/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7331 - mse: 0.7331
37/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7125 - mse: 0.7125
 70%|███████   | 7/10 [02:43<01:09, 23.22s/trial, best loss: 0.4538724422454834]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.6844 - mse: 0.6844 - val_loss: 0.5793 - val_mse: 0.5793

Epoch 3/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 45ms/step - loss: 0.9090 - mse: 0.9090
20/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6387 - mse: 0.6387
38/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6082 - mse: 0.6082
 70%|███████   | 7/10 [02:44<01:09, 23.22s/trial, best loss: 0.4538724422454834]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.5729 - mse: 0.5729 - val_loss: 0.5494 - val_mse: 0.5494

Epoch 4/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 47ms/step - loss: 0.6046 - mse: 0.6046
20/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5658 - mse: 0.5658
37/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5531 - mse: 0.5531
 70%|███████   | 7/10 [02:44<01:09, 23.22s/trial, best loss: 0.4538724422454834]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.5442 - mse: 0.5442 - val_loss: 0.4960 - val_mse: 0.4960

Epoch 5/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 53ms/step - loss: 0.8166 - mse: 0.8166
17/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5983 - mse: 0.5983
35/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5665 - mse: 0.5665
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.5289 - mse: 0.5289 - val_loss: 0.5060 - val_mse: 0.5060

Epoch 6/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 51ms/step - loss: 0.6106 - mse: 0.6106
20/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5301 - mse: 0.5301
34/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5347 - mse: 0.5347
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.5221 - mse: 0.5221 - val_loss: 0.5726 - val_mse: 0.5726

Epoch 7/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 50ms/step - loss: 0.5113 - mse: 0.5113
18/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5532 - mse: 0.5532
37/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5487 - mse: 0.5487
 70%|███████   | 7/10 [02:46<01:09, 23.22s/trial, best loss: 0.4538724422454834]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.5163 - mse: 0.5163 - val_loss: 0.4903 - val_mse: 0.4903

Epoch 8/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 53ms/step - loss: 0.3359 - mse: 0.3359
15/49 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.4677 - mse: 0.4677
34/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4938 - mse: 0.4938
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.5175 - mse: 0.5175 - val_loss: 0.6431 - val_mse: 0.6431

Epoch 9/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - loss: 0.6077 - mse: 0.6077
19/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5303 - mse: 0.5303
38/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5292 - mse: 0.5292
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.5057 - mse: 0.5057 - val_loss: 0.5955 - val_mse: 0.5955

Epoch 10/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 47ms/step - loss: 0.6900 - mse: 0.6900
19/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5192 - mse: 0.5192
38/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5217 - mse: 0.5217
 70%|███████   | 7/10 [02:47<01:09, 23.22s/trial, best loss: 0.4538724422454834]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.5091 - mse: 0.5091 - val_loss: 0.4827 - val_mse: 0.4827

 1/13 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.5042 - mse: 0.5042
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4827 - mse: 0.4827

 70%|███████   | 7/10 [02:48<01:09, 23.22s/trial, best loss: 0.4538724422454834]

2026/05/01 12:15:27 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

🏃 View run capricious-zebra-690 at: http://127.0.0.1:5000/#/experiments/4/runs/1bc24e7e1a0d4510b351cb2e34a76769

🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

 80%|████████  | 8/10 [03:03<00:46, 23.10s/trial, best loss: 0.4538724422454834]

Epoch 1/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 47s 983ms/step - loss: 38.2184 - mse: 38.2184
16/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.5640 - mse: 11.5640
29/49 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.2100 - mse: 8.2100
45/49 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3344 - mse: 6.3344
 80%|████████  | 8/10 [03:05<00:46, 23.10s/trial, best loss: 0.4538724422454834]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - loss: 2.4222 - mse: 2.4222 - val_loss: 0.6947 - val_mse: 0.6947

Epoch 2/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 52ms/step - loss: 0.7975 - mse: 0.7975
18/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.0047 - mse: 1.0047
35/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9274 - mse: 0.9274
 80%|████████  | 8/10 [03:06<00:46, 23.10s/trial, best loss: 0.4538724422454834]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.7272 - mse: 0.7272 - val_loss: 0.5171 - val_mse: 0.5171

Epoch 3/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 50ms/step - loss: 0.5977 - mse: 0.5977
19/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5610 - mse: 0.5610
36/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5727 - mse: 0.5727
 80%|████████  | 8/10 [03:07<00:46, 23.10s/trial, best loss: 0.4538724422454834]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.5755 - mse: 0.5755 - val_loss: 0.4887 - val_mse: 0.4887

Epoch 4/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 51ms/step - loss: 0.3616 - mse: 0.3616
19/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4855 - mse: 0.4855
37/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5111 - mse: 0.5111
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.5633 - mse: 0.5633 - val_loss: 0.5655 - val_mse: 0.5655

Epoch 5/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 46ms/step - loss: 0.3263 - mse: 0.3263
19/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5074 - mse: 0.5074
37/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5331 - mse: 0.5331
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5573 - mse: 0.5573 - val_loss: 0.5042 - val_mse: 0.5042

Epoch 6/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 55ms/step - loss: 0.4369 - mse: 0.4369
19/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5474 - mse: 0.5474
39/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5614 - mse: 0.5614
 80%|████████  | 8/10 [03:08<00:46, 23.10s/trial, best loss: 0.4538724422454834]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.5629 - mse: 0.5629 - val_loss: 0.4656 - val_mse: 0.4656

Epoch 7/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 59ms/step - loss: 0.5114 - mse: 0.5114
19/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4866 - mse: 0.4866
34/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4988 - mse: 0.4988
 80%|████████  | 8/10 [03:08<00:46, 23.10s/trial, best loss: 0.4538724422454834]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.5236 - mse: 0.5236 - val_loss: 0.4599 - val_mse: 0.4599

Epoch 8/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - loss: 0.4485 - mse: 0.4485
20/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5590 - mse: 0.5590
37/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5399 - mse: 0.5399
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.5335 - mse: 0.5335 - val_loss: 0.5107 - val_mse: 0.5107

Epoch 9/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 55ms/step - loss: 0.4759 - mse: 0.4759
15/49 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.5438 - mse: 0.5438
29/49 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.5429 - mse: 0.5429
48/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5295 - mse: 0.5295
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.5194 - mse: 0.5194 - val_loss: 0.4669 - val_mse: 0.4669

Epoch 10/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - loss: 0.4950 - mse: 0.4950
19/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5330 - mse: 0.5330
38/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5223 - mse: 0.5223
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.5182 - mse: 0.5182 - val_loss: 0.4892 - val_mse: 0.4892

 1/13 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.5249 - mse: 0.5249
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4892 - mse: 0.4892

 80%|████████  | 8/10 [03:11<00:46, 23.10s/trial, best loss: 0.4538724422454834]

2026/05/01 12:15:50 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

🏃 View run thoughtful-grouse-80 at: http://127.0.0.1:5000/#/experiments/4/runs/2ce5127c4fbf49d39b8cd16858fd343c

🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

 90%|█████████ | 9/10 [03:26<00:23, 23.15s/trial, best loss: 0.4538724422454834]

Epoch 1/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 45s 955ms/step - loss: 33.1810 - mse: 33.1810
11/49 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 19.2285 - mse: 19.2285
23/49 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 12.9725 - mse: 12.9725
37/49 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 9.7102 - mse: 9.7102
 90%|█████████ | 9/10 [03:28<00:23, 23.15s/trial, best loss: 0.4538724422454834]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 2.8809 - mse: 2.8809 - val_loss: 0.5378 - val_mse: 0.5378

Epoch 2/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 60ms/step - loss: 0.6566 - mse: 0.6566
18/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6042 - mse: 0.6042
35/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5759 - mse: 0.5759
 90%|█████████ | 9/10 [03:29<00:23, 23.15s/trial, best loss: 0.4538724422454834]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.5545 - mse: 0.5545 - val_loss: 0.5088 - val_mse: 0.5088

Epoch 3/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - loss: 0.4657 - mse: 0.4657
19/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4923 - mse: 0.4923
37/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5091 - mse: 0.5091
 90%|█████████ | 9/10 [03:30<00:23, 23.15s/trial, best loss: 0.4538724422454834]

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.5371 - mse: 0.5371 - val_loss: 0.4618 - val_mse: 0.4618

Epoch 4/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 45ms/step - loss: 0.5713 - mse: 0.5713
20/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5179 - mse: 0.5179
40/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5001 - mse: 0.5001
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.5173 - mse: 0.5173 - val_loss: 0.4873 - val_mse: 0.4873

Epoch 5/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 53ms/step - loss: 0.5221 - mse: 0.5221
19/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5524 - mse: 0.5524
37/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5263 - mse: 0.5263
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.5044 - mse: 0.5044 - val_loss: 0.4898 - val_mse: 0.4898

Epoch 6/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 3s 65ms/step - loss: 0.6786 - mse: 0.6786
20/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5289 - mse: 0.5289
37/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5106 - mse: 0.5106
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.4904 - mse: 0.4904 - val_loss: 0.5579 - val_mse: 0.5579

Epoch 7/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 49ms/step - loss: 0.4461 - mse: 0.4461
20/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5355 - mse: 0.5355
39/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5253 - mse: 0.5253
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.5145 - mse: 0.5145 - val_loss: 0.4630 - val_mse: 0.4630

Epoch 8/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 59ms/step - loss: 0.3182 - mse: 0.3182
21/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4379 - mse: 0.4379
39/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4676 - mse: 0.4676
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4967 - mse: 0.4967 - val_loss: 0.4821 - val_mse: 0.4821

Epoch 9/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 47ms/step - loss: 0.3969 - mse: 0.3969
20/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4534 - mse: 0.4534
37/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4678 - mse: 0.4678
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.4878 - mse: 0.4878 - val_loss: 0.4787 - val_mse: 0.4787

Epoch 10/10

 1/49 ━━━━━━━━━━━━━━━━━━━━ 2s 44ms/step - loss: 0.4170 - mse: 0.4170
20/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4749 - mse: 0.4749
38/49 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4896 - mse: 0.4896
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4966 - mse: 0.4966 - val_loss: 0.4673 - val_mse: 0.4673

 1/13 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.4789 - mse: 0.4789
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4673 - mse: 0.4673

 90%|█████████ | 9/10 [03:34<00:23, 23.15s/trial, best loss: 0.4538724422454834]

2026/05/01 12:16:13 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

🏃 View run upbeat-wren-263 at: http://127.0.0.1:5000/#/experiments/4/runs/f8cc2ed347e04652b219677d6cf226cb

🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

100%|██████████| 10/10 [03:50<00:00, 23.03s/trial, best loss: 0.4538724422454834]

2026/05/01 12:16:29 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

Best Hyperparameters: {'learning_rate': np.float64(0.09793152182150718), 'momentum': np.float64(0.08697887382780649)}
Best Evaluation RMSE: 0.4538724422454834
🏃 View run handsome-asp-465 at: http://127.0.0.1:5000/#/experiments/4/runs/0016f57cade745619a2c5f096f5a5076
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4